{
 "title": "Rack / UPS Metrics",
 "description": "Monitor your UPS over NUT service. Uses HON95/prometheus-nut-exporter and DRuggeri/nut_exporter",
 "tags": [
  "nut",
  "ups"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ups", "label": "UPS", "query": { "query": "nut_ups_info" } },
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" },
   { "name": "Preis", "label": "Preis (pro kWh)", "query": "0.2857" }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_status{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Watts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_load{ups=~\"${ups:pipe}\"} * nut_real_power_nominal_watts{ups=~\"${ups:pipe}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Charge (in %)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_battery_charge{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_load{ups=~\"${ups}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Usage per Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "$A * 24 / 1000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Usage per Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "($A * 24 / 1000) * 31",
     "type": "math"
    }
   ]
  },
  {
   "title": "Usage per Year",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "($A * 24 / 1000) * 365",
     "type": "math"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime_seconds{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Cost per Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "(($A * 24 / 1000) ) * $B",
     "type": "math"
    }
   ]
  },
  {
   "title": "Cost per Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "(($A * 24 / 1000) * $D) * $B",
     "type": "math"
    }
   ]
  },
  {
   "title": "Cost per Year",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "(($A * 24 / 1000) * 365) * $B",
     "type": "math"
    }
   ]
  },
  {
   "title": "Runtime [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_runtime_seconds{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Powerdraw",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "nut_load{$ups=\"$ups\"} * nut_real_power_nominal_watts{$ups=\"$ups\"}",
     "legendFormat": "Raw"
    },
    {
     "expr": "avg_over_time(nut_load{$ups=\"$ups\"}[$smoothing_interval]) * nut_real_power_nominal_watts{$ups=\"$ups\"}",
     "legendFormat": "Smooth $smoothing_interval"
    }
   ]
  },
  {
   "title": "Load [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_load{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Charge & Temperature [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg_over_time(nut_battery_charge{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}} Current"
    },
    {
     "expr": "100 * avg_over_time(nut_battery_charge_low{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}} Low"
    },
    {
     "expr": "avg_over_time(nut_temperature_celsius{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "Temp"
    }
   ]
  },
  {
   "title": "Input Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_input_voltage_volts{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Status Change",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nut_ups_status{status=~\"OL|OB|LB\"} > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Input Frequency [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_input_frequency_hertz{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_output_voltage_volts{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "nut_ups_info{ups=~\"${ups:pipe}\"}"
    }
   ]
  },
  {
   "title": "Output Frequency [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_output_frequency_hertz{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  { "title": "Historical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Watt per Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(\n  (nut_load{ups=\"$ups\"} * nut_real_power_nominal_watts{ups=\"$ups\"})[1d:1m]\n) / 60) by (ups)",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Watt per Week",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(\n  (nut_load{ups=\"$ups\"} * nut_real_power_nominal_watts{ups=\"$ups\"})[1w:1m]\n) / 60 ) by (ups)",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Cost per Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(\n  (nut_load{ups=\"$ups\"} * nut_real_power_nominal_watts{ups=\"$ups\"})[1d:1m]\n) / 60 * $Preis / 1000) by (ups)",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Cost per Week",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(\n  (nut_load{ups=\"$ups\"} * nut_real_power_nominal_watts{ups=\"$ups\"})[1w:1m]\n) / 60 * $Preis / 1000) by (ups)",
     "legendFormat": "{{ups}}"
    }
   ]
  }
 ]
}