{
 "title": "Rack / Shelly Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "shelly",
    "query": {
     "query": "label_values(shelly_device_info,device_name)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(shelly_device_info{device_name=~\"$shelly\"},device_mac)"
    }
   },
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" },
   { "name": "offset", "label": "Compare offset", "query": "1h,1d,1w" },
   { "name": "Preis", "label": "Preis (pro kWh)", "query": "0.266" }
  ]
 },
 "panels": [
  {
   "title": "Usage per Day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(shelly_switch_energy{device_mac=~\"$device\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage per Month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(shelly_switch_energy{device_mac=~\"$device\"}[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage per Year (predicted)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(shelly_switch_energy{device_mac=~\"$device\"}[30d])) * 12",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(shelly_switch_power{device_mac=~\"$device\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption contribution [last]",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(shelly_switch_power * on (device_mac) group_left(device_name) shelly_device_info) by (device_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(shelly_cover_power * on (device_mac) group_left(device_name) shelly_device_info) by (device_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption contribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(shelly_switch_power * on (device_mac) group_left(device_name) shelly_device_info) by (device_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(shelly_cover_power * on (device_mac) group_left(device_name) shelly_device_info) by (device_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage per Day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "(($A / 1000) ) * $B", "type": "math" }
   ]
  },
  {
   "title": "Usage per Day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "(($A / 1000) ) * $B", "type": "math" }
   ]
  },
  {
   "title": "Usage per Day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "(($A / 1000) * 12 ) * $B", "type": "math" }
   ]
  },
  {
   "title": "Powerdraw",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(shelly_switch_power{device_mac=~\"$device\"})",
     "legendFormat": "Raw"
    },
    {
     "expr": "sum(avg_over_time(shelly_switch_power{device_mac=~\"$device\"}[$smoothing_interval]))",
     "legendFormat": "Smooth $smoothing_interval"
    },
    {
     "expr": "sum(shelly_switch_power{device_mac=~\"$device\"} offset $offset)",
     "legendFormat": "Raw offset by $offset"
    },
    {
     "expr": "sum(avg_over_time(shelly_switch_power{device_mac=~\"$device\"}[$smoothing_interval] offset $offset))",
     "legendFormat": "Smooth $smoothing_interval offset by $offset"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(shelly_switch_power{device_mac=~\"$device\"}) by (device_mac) / sum(shelly_switch_power_limit{device_mac=~\"$device\"}) by (device_mac)",
     "legendFormat": "Load"
    },
    {
     "expr": "sum(shelly_switch_temperature{device_mac=~\"$device\",temperature_unit=\"dC\"}) by (device_mac)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(shelly_switch_voltage{device_mac=~\"$device\"}) by (device_mac)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(shelly_switch_current{device_mac=~\"$device\"}) by (device_mac)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(shelly_switch_power{device_mac=~\"$device\"}) by (device_mac)",
     "legendFormat": "__auto"
    },
    {
     "expr": "shelly_device_info{device_mac=~\"$device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(shelly_system_uptime{device_mac=~\"$device\"}) by (device_mac)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(shelly_switch_energy) by (device_mac)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage today",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    (\n      sum(shelly_switch_energy{device_mac=~\"$device\"})\n      by (device_mac)\n      -\n      sum(shelly_switch_energy{device_mac=~\"$device\"}  offset ${__to:date:HH}h${__to:date:mm}m)\n      by (device_mac)\n    )\n    or\n    sum(shelly_switch_energy{device_mac=~\"$device\"})\n    by (device_mac)\n  )\n  * on(device_mac) group_left(device_name) shelly_device_info\n)\nby (device_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage this month",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    (\n      sum(shelly_switch_energy{device_mac=~\"$device\"})\n      by (device_mac)\n      -\n      sum(shelly_switch_energy{device_mac=~\"$device\"}  offset ${__to:date:DD}d)\n      by (device_mac)\n    )\n    or\n    sum(shelly_switch_energy{device_mac=~\"$device\"})\n    by (device_mac)\n  )\n  * on(device_mac) group_left(device_name) shelly_device_info\n)\nby (device_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Energy Use (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum((sum(shelly_switch_energy{device_mac=~\"$device\"}) by (device_mac) - sum(shelly_switch_energy{device_mac=~\"$device\"} offset 24h) by (device_mac)) * on (device_mac) group_left(device_name) sum(shelly_device_info) by (device_mac, device_name)) by (device_name)",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "WiFi RSSI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "min(shelly_wifi_rssi{device_mac=~\"$device\"} * on (device_mac) group_left(ip) shelly_wifi_status * on (device_mac) group_left(device_name) shelly_device_info) by (device_name, ip)",
     "legendFormat": "{{device_name}} - {{ip}}"
    }
   ]
  }
 ]
}