{
 "title": "Rack / Shelly Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "shelly",
    "query": {
     "query": "label_values(shelly_device_info,device_name)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(shelly_device_info{device_name=\"$shelly\"},device_mac)"
    }
   },
   {
    "name": "switch",
    "label": "Switch",
    "query": {
     "query": "label_values(shelly_switch_state{device_mac=\"$device\"},switch_id)"
    }
   },
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" },
   { "name": "Preis", "label": "Preis (pro kWh)", "query": "0.279" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Powerdraw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(shelly_switch_power) + sum(shelly_cover_power)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption contribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(shelly_switch_power * on (device_mac) group_left(device_name) shelly_device_info) by (device_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(shelly_cover_power * on (device_mac) group_left(device_name) shelly_device_info) by (device_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Usage per Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(shelly_switch_energy{device_mac=\"$device\"}[24h])) by (device_mac)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage per Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(shelly_switch_energy{device_mac=\"$device\"}[7d])) by (device_mac) * 4"
    }
   ]
  },
  {
   "title": "Usage per Year (predicted)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(shelly_switch_energy{device_mac=\"$device\"}[7d])) by (device_mac) * 52",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "shelly_switch_power{switch_id=~\"$switch\", device_mac=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shelly_switch_power{switch_id=~\"$switch\", device_mac=\"$device\"} / shelly_switch_power_limit{switch_id=~\"$switch\", device_mac=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "shelly_switch_state{switch_id=~\"$switch\", device_mac=\"$device\"}",
     "legendFormat": "{{switch_id}}"
    }
   ]
  },
  {
   "title": "Cost per Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "(($A * 24 / 1000) ) * $B",
     "type": "math"
    }
   ]
  },
  {
   "title": "Cost per Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "(($A * 24 / 1000) * $D) * $B",
     "type": "math"
    }
   ]
  },
  {
   "title": "Cost per Year",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "(($A * 24 / 1000) * 365) * $B",
     "type": "math"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "shelly_system_uptime{device_mac=\"$device\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Powerdraw",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(shelly_switch_power{switch_id=~\"$switch\", device_mac=\"$device\"}) by (device_mac)",
     "legendFormat": "Raw"
    },
    {
     "expr": "sum(avg_over_time(shelly_switch_power{switch_id=~\"$switch\", device_mac=\"$device\"}[$smoothing_interval])) by (device_mac)",
     "legendFormat": "Smooth $smoothing_interval"
    }
   ]
  },
  {
   "title": "Load [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(shelly_switch_power{switch_id=~\"$switch\", device_mac=\"$device\"}) by (device_mac) / sum(shelly_switch_power_limit{switch_id=~\"$switch\", device_mac=\"$device\"}) by (device_mac)",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(shelly_switch_temperature{device_mac=\"$device\",temperature_unit=\"dC\"}) by (device_mac)",
     "legendFormat": "{{device_mac}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "sum(shelly_switch_voltage{device_mac=\"$device\"}) by (switch_id)",
     "legendFormat": "{{switch_id}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "sum(shelly_switch_current{device_mac=\"$device\"}) by (switch_id)",
     "legendFormat": "{{switch_id}}"
    }
   ]
  },
  {
   "title": "Status Change",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(shelly_switch_state{device_mac=\"$device\"}) by (switch_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Historical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Watt per Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "shelly_switch_energy{device_mac=\"$device\"} - shelly_switch_energy{device_mac=\"$device\"} offset 24h",
     "legendFormat": "{{device_mac}}"
    }
   ]
  },
  {
   "title": "Cost per Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum((shelly_switch_energy{device_mac=\"$device\"} - shelly_switch_energy{device_mac=\"$device\"} offset 24h) * $Preis / 1000) by (device_mac)",
     "legendFormat": "{{device_mac}}"
    }
   ]
  },
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{container=\"shelly-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "go_goroutines{container=\"shelly-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"shelly-exporter\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}