{
 "title": "Speedtest",
 "tags": [ "truenas" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "max(speedtest_download_bytes_second) by (job) / 125000",
     "legendFormat": "Download"
    },
    {
     "expr": "max(speedtest_upload_bytes_second) by (job) * -1 / 125000",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(speedtest_ping_jitter_seconds) by (job)",
     "legendFormat": "Jitter"
    },
    {
     "expr": "max(speedtest_ping_latency_seconds) by (job)",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(speedtest_packet_loss_pct) by (job)",
     "legendFormat": "Loss"
    }
   ]
  },
  {
   "title": "Test duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(speedtest_scrape_duration_seconds) by (job)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "max(speedtest_download_bytes_second) by (server_name, server_location, server_host, server_country) / 125000",
     "legendFormat": "Download"
    },
    {
     "expr": "max(speedtest_upload_bytes_second) by (server_name, server_location, server_host, server_country) / 125000",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}