{
 "title": "TrueNAS Scale / Disk Insight",
 "tags": [ "truenas" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(uptime,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(uptime{job=\"$job\"},instance)"
    }
   },
   {
    "name": "disk",
    "label": "disks",
    "query": {
     "query": "label_values(disk_io{instance=\"$instance\", job=\"$job\"},disk)"
    }
   },
   { "name": "smooth", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" }
  ]
 },
 "panels": [
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{instance=~\"$instance\"}",
     "legendFormat": "synced"
    }
   ]
  },
  { "title": "Disk Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Disk utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_utilization{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_utilization{instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk utilization (smooth $smooth)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(disk_utilization{instance=~\"$instance\", disk=~\"$disk\"}[$smooth])",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Disk I/O - $disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 27 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "disk_io{instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Disk I/O Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Disk I/O time - $disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 48 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "abs(disk_iotime{instance=~\"$instance\", disk=~\"$disk\"})",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Disk IOps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Disk IOps - $disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 69 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "abs(disk_io_ops{instance=~\"$instance\", disk=~\"$disk\"})",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Disk Backlog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Disk backlog + busy - $disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 90 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "disk_io_backlog{instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "backlog"
    },
    {
     "expr": "disk_busy{instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "busy"
    }
   ]
  },
  { "title": "Disk Await", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Disk await - $disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 109 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "abs(disk_await{instance=~\"$instance\", disk=~\"$disk\"})",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Disk Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Disk active operations - $disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 128 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "disk_qops{instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "value"
    }
   ]
  },
  { "title": "Disk I/O Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Disk avg I/O size - $disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 147 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "abs(disk_io_size{instance=~\"$instance\", disk=~\"$disk\"})",
     "legendFormat": "{{op}}"
    }
   ]
  }
 ]
}